let data={holidays:[],destinations:[],places:[],travel:[]},activeHoliday=null,activeDestination=null,showPrevious=false,markers=new Map();
const today=new Date().toISOString().slice(0,10),categoryLabels={hotel:'Hotel',food:'Eat & drink',activity:'See & do'};
const travelIcons={flight:'✈',train:'🚆',ferry:'⛴',coach:'🚌',car:'🚗',taxi:'🚕',other:'↗'};
const palettes={city:['#1c6655','#dc9b3f','#fbf8f1'],beach:['#087f8c','#ff8c6b','#fff8e7'],wildlife:['#355d3a','#c58b45','#f6f1e4'],winter:['#365b7d','#9ac7df','#f4f8fb'],roadtrip:['#8c3f2d','#e5a84b','#fff5e8'],teal:['#137b78','#45b6ad','#f1f9f7'],blue:['#295c9b','#62a7df','#f1f6fb'],purple:['#62458b','#b181d0','#f8f2fa'],orange:['#a65325','#ec9d3f','#fff7eb'],green:['#376b3e','#77a95a','#f4f8ef'],mono:['#343a3d','#8b969b','#f5f5f4']};
const markerSource=new ol.source.Vector(),map=new ol.Map({target:'map',layers:[new ol.layer.Tile({source:new ol.source.XYZ({url:'/tiles/{z}/{x}/{y}.png',maxZoom:19,attributions:'© OpenStreetMap contributors'})}),new ol.layer.Vector({source:markerSource})],view:new ol.View({center:ol.proj.fromLonLat([0,20]),zoom:2})});
const popup=document.createElement('div');popup.className='map-popup';document.querySelector('#map').append(popup);const popupOverlay=new ol.Overlay({element:popup,positioning:'bottom-center',offset:[0,-18],stopEvent:true});map.addOverlay(popupOverlay);
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],esc=value=>{const d=document.createElement('div');d.textContent=value??'';return d.innerHTML};
function holiday(){return data.holidays.find(h=>h.id===activeHoliday)}function destination(){return data.destinations.find(d=>d.id===activeDestination)}
function dates(start,end){const out=[],d=new Date(start+'T12:00:00Z'),last=new Date(end+'T12:00:00Z');while(d<=last){out.push(d.toISOString().slice(0,10));d.setUTCDate(d.getUTCDate()+1)}return out}
function niceDate(value,opts={day:'numeric',month:'short',year:'numeric'}){return new Intl.DateTimeFormat('en-GB',opts).format(new Date(value+'T12:00:00Z'))}
function dateRange(a,b){return `${niceDate(a)}–${niceDate(b)}`}
function nights(a,b){return Math.max(0,Math.round((new Date(b)-new Date(a))/86400000))}
function flag(code){return [...String(code||'').toUpperCase()].map(c=>String.fromCodePoint(127397+c.charCodeAt())).join('')}
async function api(path,options={}){const response=await fetch(path,{headers:{'Content-Type':'application/json'},...options});const result=await response.json();if(!response.ok)throw new Error(result.error||'Something went wrong');return result}
async function refresh(preferredHoliday=activeHoliday,preferredDestination=activeDestination){data=await api('/api/state');const current=data.holidays.filter(h=>h.end_date>=today),past=data.holidays.filter(h=>h.end_date<today);if(!current.length&&past.length)showPrevious=true;let pool=showPrevious?past:current;if(!pool.length)pool=showPrevious?current:past;activeHoliday=pool.some(h=>h.id===preferredHoliday)?preferredHoliday:(pool[0]?.id||data.holidays[0]?.id||null);const ds=data.destinations.filter(d=>d.holiday_id===activeHoliday);activeDestination=ds.some(d=>d.id===preferredDestination)?preferredDestination:(ds[0]?.id||null);render()}
function applyTheme(h){let p=palettes[h.theme]||palettes.city;if(h.theme==='custom')p=[h.primary_color||'#1c6655',h.accent_color||'#dc9b3f','#fbf8f1'];document.documentElement.style.setProperty('--green',p[0]);document.documentElement.style.setProperty('--gold',p[1]);document.documentElement.style.setProperty('--paper',p[2]);document.documentElement.style.setProperty('--hero-start',p[0]);document.documentElement.style.setProperty('--hero-end',p[1]);document.body.dataset.theme=h.theme}
function render(){if(!data.holidays.length){openHoliday(true);return}const h=holiday();applyTheme(h);document.title=`${h.name} · Holiday planner`;$('#holiday-title').textContent=h.name;$('#holiday-subtitle').textContent=h.subtitle||'Plan the places, journeys and days that make the trip yours.';$('#holiday-dates').textContent=dateRange(h.start_date,h.end_date);$('#holiday-status').textContent=h.status==='booked'?'✓ Holiday booked':'◌ Holiday being planned';const hds=data.destinations.filter(d=>d.holiday_id===h.id);$('#banner-flags').textContent=[...new Set(hds.map(d=>flag(d.country_code)))].join(' ')||'TRIP PLANNER';renderHolidaySelector();renderTabs(hds);$('#empty-holiday').classList.toggle('hidden',hds.length>0);if(!hds.length){$('#destination-view').classList.add('hidden');$('#overall-view').classList.add('hidden');return}const overall=activeDestination==='overall';$('#destination-view').classList.toggle('hidden',overall);$('#overall-view').classList.toggle('hidden',!overall);overall?renderOverall(h,hds):renderDestination(destination());}
function renderHolidaySelector(){const sel=$('#holiday-select'),wanted=data.holidays.filter(h=>showPrevious?h.end_date<today:h.end_date>=today),items=wanted.length?wanted:data.holidays.filter(h=>showPrevious?h.end_date>=today:h.end_date<today),previous=$('#previous-toggle');sel.innerHTML=items.map(h=>`<option value="${h.id}">${esc(h.name)}</option>`).join('');sel.value=activeHoliday||'';previous.classList.toggle('active',showPrevious);previous.classList.toggle('hidden',!data.holidays.some(h=>h.end_date<today));previous.textContent=showPrevious?'Upcoming holidays':'Previous holidays'}
function renderTabs(ds){const tabs=$('#tabs');tabs.textContent='';ds.forEach(d=>{const b=document.createElement('button');b.className='tab'+(d.id===activeDestination?' active':'');b.innerHTML=`<span>${flag(d.country_code)} ${esc(d.name)}</span><small>${niceDate(d.start_date,{day:'numeric',month:'short'})}–${niceDate(d.end_date,{day:'numeric',month:'short'})}</small>`;b.onclick=()=>{activeDestination=d.id;render()};tabs.append(b)});const overall=document.createElement('button');overall.className='tab'+(activeDestination==='overall'?' active':'');overall.innerHTML='<span>Whole trip</span><small>Calendar & travel</small>';overall.onclick=()=>{activeDestination='overall';render()};tabs.append(overall);const add=document.createElement('button');add.className='tab add-tab';add.innerHTML='<span>＋ Destination</span><small>Add another city</small>';add.onclick=()=>openDestination();tabs.append(add)}
function markerStyle(category){return new ol.style.Style({image:new ol.style.Circle({radius:18,fill:new ol.style.Fill({color:{hotel:'#d9634b',food:'#dc9b3f',activity:'#427ba8'}[category]}),stroke:new ol.style.Stroke({color:'#fff',width:3})}),text:new ol.style.Text({text:{hotel:'🛏',food:'🍽',activity:'★'}[category],font:'bold 16px sans-serif',fill:new ol.style.Fill({color:'#fff'})})})}
function showPopup(place,coord){popup.innerHTML=`<div class="popup-kind">${categoryLabels[place.category]}</div><div class="popup-name">${esc(place.name)}</div><a href="${encodeURI(place.url)}" target="_blank" rel="noopener">Open in Google Maps ↗</a>`;popupOverlay.setPosition(coord)}
map.on('singleclick',e=>{const f=map.forEachFeatureAtPixel(e.pixel,x=>x);f?showPopup(f.get('place'),f.getGeometry().getCoordinates()):popupOverlay.setPosition(undefined)});
function renderDestination(d){$('#country').textContent=`${flag(d.country_code)} ${d.country.toUpperCase()}`;$('#city-title').textContent=d.name;$('#night-count').textContent=`${nights(d.start_date,d.end_date)} nights`;$('#date-range').textContent=dateRange(d.start_date,d.end_date);markerSource.clear();markers.clear();popupOverlay.setPosition(undefined);renderCalendar(d);$$('.place-panel').forEach(panel=>{const category=panel.dataset.category,holder=panel.querySelector('.entries');holder.textContent='';data.places.filter(p=>p.destination_id===d.id&&p.category===category).forEach(place=>{const node=$('#saved-template').content.cloneNode(true),validDays=dates(d.start_date,d.end_date),out=place.schedule_date&&!validDays.includes(place.schedule_date);node.querySelector('strong').textContent=place.name;if(place.url){node.querySelector('a').href=place.url;node.querySelector('.focus-place').onclick=()=>focusPlace(place.id)}else{node.querySelector('a').remove();node.querySelector('.focus-place span').textContent='Free-text idea';node.querySelector('.focus-place').disabled=true}node.querySelector('.delete').onclick=()=>removeItem('places',place.id,'Remove this saved place or idea?');const warning=node.querySelector('.out-of-range');if(out){warning.classList.remove('hidden');warning.textContent=`Unscheduled — previously on ${niceDate(place.schedule_date)}.`}const day=node.querySelector('.day-select');day.innerHTML='<option value="">Day…</option>'+validDays.map(x=>`<option value="${x}">${niceDate(x,{weekday:'short',day:'numeric',month:'short'})}</option>`).join('');day.value=out?'':(place.schedule_date||'');node.querySelector('.period-select').value=out?'':(place.schedule_period||'');node.querySelector('.schedule-button').onclick=e=>schedule(e,place.id);holder.append(node);if(place.latitude!==null){const m=new ol.Feature({geometry:new ol.geom.Point(ol.proj.fromLonLat([place.longitude,place.latitude])),place});m.setStyle(markerStyle(category));markerSource.addFeature(m);markers.set(place.id,m)}});const f=$('#form-template').content.cloneNode(true);f.querySelector('form').onsubmit=e=>addPlace(e,category);holder.append(f);if(category==='activity'){const t=$('#text-form-template').content.cloneNode(true);t.querySelector('form').onsubmit=addIdea;holder.append(t)}});const visible=data.places.filter(p=>p.destination_id===d.id&&p.latitude!==null);if(visible.length)map.getView().fit(ol.extent.boundingExtent(visible.map(p=>ol.proj.fromLonLat([p.longitude,p.latitude]))),{padding:[70,70,70,70],maxZoom:15});else{map.getView().setCenter(ol.proj.fromLonLat([d.longitude,d.latitude]));map.getView().setZoom(12)}setTimeout(()=>map.updateSize(),50)}
function calendarColumn(day,places,journeys=[]){const col=document.createElement('article');col.className='calendar-day';col.innerHTML=`<div class="day-heading"><strong>${niceDate(day,{weekday:'long'})}</strong><span>${niceDate(day,{day:'numeric',month:'short'})}</span></div>`;['morning','afternoon','evening','night'].forEach(period=>{const slot=document.createElement('div');slot.className='period';slot.innerHTML=`<strong>${period}</strong>`;let count=0;journeys.filter(j=>j.departure_at.slice(0,10)===day&&timePeriod(j.departure_at)===period).forEach(j=>{slot.append(travelNode(j,true));count++});places.filter(p=>p.schedule_date===day&&p.schedule_period===period).forEach(p=>{const b=document.createElement('button');b.className=`calendar-place ${p.category}`;b.textContent=p.name;b.onclick=()=>{const d=data.destinations.find(x=>x.id===p.destination_id);activeDestination=d.id;render();setTimeout(()=>focusPlace(p.id),50)};slot.append(b);count++});if(!count)slot.insertAdjacentHTML('beforeend','<span class="empty-slot">Nothing planned</span>');col.append(slot)});return col}
function renderCalendar(d){const holder=$('#calendar');holder.textContent='';const ps=data.places.filter(p=>p.destination_id===d.id);dates(d.start_date,d.end_date).forEach(day=>holder.append(calendarColumn(day,ps)))}
function timePeriod(value){const hour=Number(value.slice(11,13));return hour<12?'morning':hour<17?'afternoon':hour<22?'evening':'night'}
function renderOverall(h,ds){$('#overall-title').textContent=dateRange(h.start_date,h.end_date);$('#overall-route').textContent=ds.map(d=>d.name).join(' → ');const journeys=data.travel.filter(j=>j.holiday_id===h.id),booked=journeys.filter(j=>j.status==='booked').length;$('#overall-progress').textContent=h.status==='booked'?'Holiday booked':'Holiday planned';$('#overall-summary').textContent=`${booked} of ${journeys.length} journeys booked · ${ds.length} destinations`;const strip=$('#journey-strip');strip.textContent='';journeys.forEach(j=>strip.append(travelNode(j,false)));if(!journeys.length)strip.innerHTML='<p class="empty-message">No journeys added yet.</p>';const cal=$('#overall-calendar');cal.textContent='';const ps=data.places.filter(p=>ds.some(d=>d.id===p.destination_id));dates(h.start_date,h.end_date).forEach(day=>cal.append(calendarColumn(day,ps,journeys)))}
function travelNode(j,compact){const node=document.createElement(compact?'div':'article');node.className=(compact?'travel-event':'journey-card')+(j.status==='planned'?' tentative':'');const dtText=`${niceDate(j.departure_at.slice(0,10),{day:'numeric',month:'short'})} ${j.departure_at.slice(11,16)}`;node.innerHTML=compact?`<b>${travelIcons[j.travel_type]} ${esc(j.service_number||capitalize(j.travel_type))}</b><span>${esc(j.from_name)} → ${esc(j.to_name)}</span><em>${j.status}</em>`:`<div><span class="status ${j.status==='planned'?'tentative':''}">${j.status}</span><strong>${travelIcons[j.travel_type]} ${esc(j.service_number||capitalize(j.travel_type))}</strong><small>${dtText}</small></div><p>${esc(j.from_name)} → ${esc(j.to_name)}</p>${j.terminal?`<small>${esc(j.terminal)}</small>`:''}${j.notes?`<small>${esc(j.notes)}</small>`:''}<div class="journey-actions"><button data-edit>Edit</button><button data-status>${j.status==='booked'?'Mark planned':'Mark booked'}</button><button data-delete>Remove</button></div>`;if(!compact){node.querySelector('[data-edit]').onclick=()=>openTravel(j);node.querySelector('[data-status]').onclick=()=>toggleTravel(j);node.querySelector('[data-delete]').onclick=()=>removeItem('travel',j.id,'Remove this journey?')}return node}
function capitalize(v){return v.charAt(0).toUpperCase()+v.slice(1)}
async function schedule(e,id){const box=e.currentTarget.closest('.saved-place'),status=box.querySelector('.schedule-status');try{await api(`/api/places/${id}`,{method:'PATCH',body:JSON.stringify({schedule_date:box.querySelector('.day-select').value,schedule_period:box.querySelector('.period-select').value})});await refresh()}catch(err){status.textContent=err.message}}
async function addPlace(e,category){e.preventDefault();const form=e.currentTarget,status=form.querySelector('.form-status');try{await api('/api/places',{method:'POST',body:JSON.stringify({destination_id:activeDestination,category,url:form.querySelector('input').value})});await refresh()}catch(err){status.textContent=err.message}}
async function addIdea(e){e.preventDefault();const form=e.currentTarget,status=form.querySelector('.form-status');try{await api('/api/places',{method:'POST',body:JSON.stringify({destination_id:activeDestination,category:'activity',name:form.querySelector('input').value})});await refresh()}catch(err){status.textContent=err.message}}
function focusPlace(id){const m=markers.get(id);if(m){const c=m.getGeometry().getCoordinates();map.getView().animate({center:c,zoom:16,duration:300});showPopup(m.get('place'),c);$('.map-card').scrollIntoView({behavior:'smooth',block:'center'})}}
async function removeItem(kind,id,message){if(!confirm(message))return;await api(`/api/${kind}/${id}`,{method:'DELETE'});await refresh()}
async function toggleTravel(j){await api(`/api/travel/${j.id}`,{method:'PATCH',body:JSON.stringify({status:j.status==='booked'?'planned':'booked'})});await refresh()}
function fill(form,values){Object.entries(values).forEach(([k,v])=>{if(form.elements[k])form.elements[k].value=v??''})}
function openHoliday(isNew=false){const form=$('#holiday-form'),h=isNew?null:holiday();form.reset();fill(form,h||{status:'planning',theme:'city',start_date:today,end_date:today,primary_color:'#1c6655',accent_color:'#dc9b3f'});form.elements.id.value=h?.id||'';form.querySelector('h2').textContent=h?'Holiday settings':'Add a holiday';$('#delete-holiday').classList.toggle('hidden',!h);$('#holiday-dialog').showModal()}
function openDestination(edit=false){const form=$('#destination-form'),d=edit?destination():null,h=holiday();form.reset();fill(form,d||{start_date:h.start_date,end_date:h.end_date,country_code:''});form.elements.id.value=d?.id||'';form.querySelector('h2').textContent=d?'Edit destination':'Add destination';$('#delete-destination').classList.toggle('hidden',!d);$('#destination-dialog').showModal()}
async function submitHoliday(e){e.preventDefault();const form=e.currentTarget,obj=Object.fromEntries(new FormData(form)),id=obj.id;delete obj.id;try{id?await api(`/api/holidays/${id}`,{method:'PATCH',body:JSON.stringify(obj)}):activeHoliday=(await api('/api/holidays',{method:'POST',body:JSON.stringify(obj)})).id;form.closest('dialog').close();showPrevious=false;await refresh(activeHoliday)}catch(err){form.querySelector('.form-status').textContent=err.message}}
async function submitDestination(e){e.preventDefault();const form=e.currentTarget,obj=Object.fromEntries(new FormData(form)),id=obj.id;delete obj.id;obj.holiday_id=activeHoliday;try{if(id)await api(`/api/destinations/${id}`,{method:'PATCH',body:JSON.stringify(obj)});else activeDestination=(await api('/api/destinations',{method:'POST',body:JSON.stringify(obj)})).id;form.closest('dialog').close();await refresh(activeHoliday,activeDestination)}catch(err){form.querySelector('.form-status').textContent=err.message}}
function openTravel(j=null){const form=$('#travel-form');form.reset();fill(form,j||{status:'planned',travel_type:'flight'});form.elements.id.value=j?.id||'';form.querySelector('h2').textContent=j?'Edit journey':'Add journey';$('#travel-dialog').showModal()}
async function submitTravel(e){e.preventDefault();const form=e.currentTarget,obj=Object.fromEntries(new FormData(form)),id=obj.id;delete obj.id;obj.holiday_id=activeHoliday;try{await api(id?`/api/travel/${id}`:'/api/travel',{method:id?'PATCH':'POST',body:JSON.stringify(obj)});form.closest('dialog').close();await refresh()}catch(err){form.querySelector('.form-status').textContent=err.message}}
$('#holiday-select').onchange=e=>{activeHoliday=Number(e.target.value);activeDestination=null;render()};$('#previous-toggle').onclick=()=>{showPrevious=!showPrevious;activeHoliday=null;activeDestination=null;refresh()};$('#new-holiday').onclick=()=>openHoliday(true);$('#edit-holiday').onclick=()=>openHoliday(false);$('#empty-add-destination').onclick=()=>openDestination();$('#edit-destination').onclick=()=>openDestination(true);$('#add-travel').onclick=()=>openTravel();$('#holiday-form').onsubmit=submitHoliday;$('#destination-form').onsubmit=submitDestination;$('#travel-form').onsubmit=submitTravel;$$('.close-dialog').forEach(b=>b.onclick=()=>b.closest('dialog').close());$('#delete-destination').onclick=async()=>{const d=destination();if(confirm(`Delete ${d.name} and all of its saved places?`)){await api(`/api/destinations/${d.id}`,{method:'DELETE'});$('#destination-dialog').close();activeDestination=null;await refresh()}};$('#delete-holiday').onclick=async()=>{const h=holiday();if(confirm(`Delete ${h.name}, all destinations, journeys and saved places?`)){await api(`/api/holidays/${h.id}`,{method:'DELETE'});$('#holiday-dialog').close();activeHoliday=null;activeDestination=null;await refresh()}};
$('#header-add-travel').onclick=()=>openTravel();
refresh().catch(err=>{document.body.innerHTML=`<main class="fatal"><h1>Holiday planner could not load</h1><p>${esc(err.message)}</p></main>`});
